name: CI with Allure Report

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Run tests (adjust command as needed)
      - name: Run tests (headless Chrome, QA)
        run: |
          ./gradlew clean test -Dheadless=true -Denv=qa

      # Install Allure CLI
      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y allure
          allure --version

      # Generate Allure Report
      - name: Generate Allure Report
        run: |
          allure generate target/allure-results --clean -o target/allure-report

      # Deploy to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/allure-report
